---
# tasks file for shariff-install
#TODO depend on a separate PHP installation role?
- name: Make sure the right group exists
  group:
    name: "{{ app__php__group }}"
    system: yes

- name: Make sure the right user exists
  user:
    name: "{{ app__php__user }}"
    group: "{{ app__php__group }}"
    home: "{{ app__php__home }}"
    comment: "Separate User for PHP"
    shell: "/bin/false"
    system: yes

- name: Download the package
  environment:
    http_proxy: "{{ http_proxy }}"
  get_url:
    checksum: "{{ app__shariff__checksum }}"
    dest: "{{ app__shariff__base }}/{{ app__shariff__package }}"
    url: "{{ app__shariff__download_upstream }}"
    owner: "{{ app__php__user }}"
    group: "{{ app__php__group }}"
    mode: "0644"

- name: Unpack shariff
  unarchive:
    remote_src: yes
    creates: "{{ app__shariff__home }}/shariff.json"
    dest: "{{ app__shariff__home }}"
    src: "{{ app__shariff__base }}/{{ app__shariff__package }}"

- name: Create the cache
  file:
    path: "{{ app__shariff__cache }}"
    state: directory
    mode: "0755"
    owner: "{{ app__php__user }}"
    group: "{{ app__php__group }}"

#- name: Configure Shariff
